FROM ghcr.io/graalvm/native-image-community:25 AS build

RUN useradd -r -m -u 1001 -U -d /home/myuser -s /bin/bash myuser && \
    mkdir -p /usr/src/app && \
    chown myuser:myuser /usr/src/app

WORKDIR /usr/src/app
USER myuser

COPY --chown=myuser:myuser .mvn .mvn
COPY --chown=myuser:myuser mvnw mvnw

COPY --chown=myuser:myuser pom.xml pom.xml
COPY --chown=myuser:myuser soloist-player-model/pom.xml soloist-player-model/pom.xml
COPY --chown=myuser:myuser soloist-player-service/pom.xml soloist-player-service/pom.xml

RUN mkdir -p /home/myuser/.m2
COPY --chown=myuser:myuser settings.xml /home/myuser/.m2/settings.xml

RUN chmod +x ./mvnw && \
    ./mvnw -q -B -DskipTests dependency:go-offline -Pnative || true

COPY --chown=myuser:myuser . .

RUN chmod +x ./mvnw && \
    ./mvnw clean package -Pnative -DskipTests

FROM alpine:3.21 AS run

RUN apk add --no-cache libc6-compat libstdc++

RUN addgroup -S myuser && adduser -S -G myuser myuser && \
    mkdir -p /app && \
    chown myuser:myuser /app

USER myuser
WORKDIR /app

COPY --from=build --chown=myuser:myuser /usr/src/app/soloist-player-service/target/soloist-player-service /app/app

EXPOSE 8080
CMD ["./app", "-Dspring.profiles.active=prod"]