spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/solo_leveling
  kafka:
    bootstrap-servers: kafka-service:9092
    properties:
      schema.registry.url: http://schema-registry-service:8081
  data:
    redis:
      host: redis
  grpc:
    server:
      port: 9090
server:
  port: 8080