apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-leveling-player
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solo-leveling-player
  template:
    metadata:
      labels:
        app: solo-leveling-player
      annotations:
        commit.sha: "${GIT_COMMIT_SHA}"
    spec:
      containers:
        - name: app
          image: $DOCKERHUB_USER/solo-leveling-player:$GIT_COMMIT_SHA
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: POSTGRES_USER
              value: "${POSTGRES_USER}"
            - name: POSTGRES_PASSWORD
              value: "${POSTGRES_PASSWORD}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5