liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  default-schema: public
jimmer:
  language: kotlin
  default-enum-strategy: ORDINAL
  show-sql: true
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect