spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
liquibase:
  enabled: true
  default-schema: public
jimmer:
  language: kotlin
  default-enum-strategy: ORDINAL
  show-sql: false
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect