name: "Build project with tests"

on:
  pull_request:
    branches-ignore: [ ]
  workflow_dispatch:

jobs:
  build:
    name: Build project with tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate settings.xml in project root
        run: |
          cat <<EOF > ./settings.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_USER}</username>
                <password>${PACKAGES_TOKEN}</password>
              </server>
            </servers>
          </settings>
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build project with Maven
        run: |
          chmod +x ./mvnw && \
          ./mvnw clean install -s ./settings.xml

      - name: Clean up temporary files (security)
        run: |
          rm -f settings.xml