name: Build Docker Image with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Create gradle.properties
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat <<EOL > gradle.properties
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          github.user=${GITHUB_USER}
          github.token=${GITHUB_TOKEN}
          EOL

      - name: Build Docker image
        run: |
          docker build -t solo-leveling-player .

      - name: Remove gradle.properties
        run: |
          rm -f gradle.properties